[project]
name = "hope-flex-fields"
version = "0.8.1"
description = ""
readme = "README.md"
license = { text = "MIT" }

authors = [
  { name = "sax", email = "s.apostolico@gmail.com" },
]

requires-python = ">=3.13"
classifiers = [
  "Environment :: Web Environment",
  "Framework :: Django",
  "Framework :: Django :: 5.2",
  "Framework :: Django :: 6.0",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dependencies = [
  "deepdiff",
  "deprecation",
  "django-admin-extra-buttons",
  "django-adminactions",
  "django-jsoneditor",
  "django-regex",
  "django-regex-field",
  "django-strategy-field",
  "djangorestframework",
  "jmespath",
  "jsonpickle",
  "mini-racer",
  "python-calamine",
  "requests",
  "xlsxwriter",
]

[dependency-groups]
dev = [
  "bandit",
  "black",
  "bump2version",
  "django-csp",
  "django-factory-boy",
  "django-webtest",
  "flake8",
  "flake8-html",
  "freezegun",
  "isort",
  "mypy",
  "pdbpp",
  "pre-commit",
  "pytest",
  "pytest-cov",
  "pytest-django",
  "pytest-xdist",
  "requests",
  "responses",
  "tox",
]

docs = [
  "mkdocs",
  "mkdocs-awesome-pages-plugin",
  "mkdocs-material",
  "mkdocstrings-python",
]

[tool.hatch.build.targets.sdist]
include = [
  "src/hope_flex_fields/**/*.*",
]

[tool.hatch.build.targets.wheel]
packages = [
  "src/hope_flex_fields",
]

[tool.django-stubs]
django_settings_module = "hope_dedup_engine.config.settings"
