# Generated by Django 3.2.25 on 2024-07-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hope_flex_fields', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datachecker',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='datacheckerfieldset',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fielddefinition',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fieldset',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='flexfield',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='datacheckerfieldset',
            name='prefix',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
