# Generated by Django 5.1.2 on 2024-10-09 10:15

from django.db import migrations

from hope_flex_fields.utils import create_default_fields


class Migration(migrations.Migration):
    dependencies = [
        (
            "hope_flex_fields",
            "0006_alter_datachecker_id_alter_datacheckerfieldset_id_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(create_default_fields),
    ]
