# Generated by Django 5.1.2 on 2024-10-25 05:35

import strategy_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hope_flex_fields", "0007_create_default_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="fielddefinition",
            name="attributes_strategy",
            field=strategy_field.fields.StrategyField(
                default="hope_flex_fields.attributes.default.DefaultAttributeHandler",
                help_text="Strategy to use for attributes retrieval",
            ),
        ),
        migrations.AlterField(
            model_name="datachecker",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="datacheckerfieldset",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="fielddefinition",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="fieldset",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="flexfield",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
