# Generated by Django 5.1.2 on 2024-10-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hope_flex_fields", "0008_fielddefinition_attributes_strategy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fielddefinition",
            name="strategy_config",
            field=models.JSONField(blank=True, default=dict, editable=False, null=True),
        ),
    ]
