# Generated by Django 5.1.2 on 2024-10-28 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hope_flex_fields", "0009_fielddefinition_strategy_config"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flexfield",
            old_name="field",
            new_name="definition",
        ),
    ]
