# Generated by Django 5.2.3 on 2025-07-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "hope_flex_fields",
            "0013_fielddefinition_validated_alter_datachecker_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="datacheckerfieldset",
            name="group",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="datacheckerfieldset",
            name="override_group_default_value",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fieldset",
            name="group",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="datachecker",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="datacheckerfieldset",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="fielddefinition",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="fieldset",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="flexfield",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
