# Generated by Django 5.1.1 on 2026-02-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "hope_flex_fields",
            "0015_alter_datachecker_id_alter_datacheckerfieldset_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldset",
            name="validation",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
